---
- name: "main playbook to control environment build"
  hosts: "INVENTORY:children"
  connection: "local"
  var_files:
    - vars/config.yml

  tasks:

- include: "roles/infra/openstack/openstack.yml"
- include: "roles/common/setup/setup-local-etc-hosts.yml"
- include: "roles/common/setup/setup-remote-hosts.yml"
