---
# type of deployment. i.e. openstack, aws, google, azure, etc
deployment_stack: google
# config used by ansible
ansible_user: ose_ansible
ansible_sudo: true
ansible_ssh_private_key_file: /Users/klimaye/Projects/finiteloop.me/ansible/ansible-playbooks/secrets/ose_ansible
# user created on each host
admin_user: admin
# Below var is required else shade component is not available to python
# Detailed discussion @ https://github.com/ansible/ansible/issues/6345
ansible_python_interpreter: "/usr/bin/env python"
