---
- name: Delete server(s)- "{{ play_hosts }}"
  gce:
    instance_names: "{{ inventory_hostname }}"
    state: absent
    service_account_email: 292893158312-compute@developer.gserviceaccount.com
    #"{{ gce_service_account_email_address }}"
    credentials_file: /var/ansible/secrets/OpenShift-V3-32605dcc9eb3.json
    #"{{ gce_credentials_file }}"
    project_id: hidden-cat-136223
