---
# - name: "Provision environment on Google"
#   hosts: "INVENTORY:children"
#   connection: local

  # # Configure access to Google compute
  # vars:
  #   gce_service_account_email: 292893158312-compute@developer.gserviceaccount.com
  #   gce_credentials_file: ../../secrets/OpenShift-V3-32605dcc9eb3.json
  #   gce_project_id: hidden-cat-136223
  #   gce_machine_type: n1-standard-2 #2vCPU and 7.5GB RAM
  #   image: rhel-7-ose-3
  #
  # tasks:
  #   # Retrieve information for each server in the inventory
- name: Provision server "{{ inventory_hostname }}"
  gce:
    instance_names: "{{ inventory_hostname }}"
    machine_type: n1-standard-2
    #"{{ gce_machine_type }}"
    image: rhel-7-ose-3
    #"{{ gce_machine_image }}"
    service_account_email: 292893158312-compute@developer.gserviceaccount.com
    #"{{ gce_service_account_email_address }}"
    credentials_file: /var/ansible/secrets/OpenShift-V3-32605dcc9eb3.json
    #"{{ gce_credentials_file }}"
    project_id: hidden-cat-136223
    #"{{ gce_project_id }}"
  register: gce
